import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "~/styles/Home.module.scss";
import * as AspectRatio from "@radix-ui/react-aspect-ratio";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>SouthPark</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.SouthHeader}>
          <h1>South Park</h1>

          <p className={styles.Description}>
            <h3>
              A political satire surrouding the lives of 4 schoolchildren of
              South Park, Colorado.
            </h3>
          </p>
        </section>
        <section className={styles.Images}>
          {/* <div
            className={styles.Image}
            style={{
              backgroundImage:
                "url('https://www.hollywoodreporter.com/wp-content/uploads/2021/10/south-park-4.jpg')",
            }}
          /> */}
          <AspectRatio.Root ratio={16 / 9}>
            <img
              src="https://www.hollywoodreporter.com/wp-content/uploads/2021/10/south-park-4.jpg"
              alt="Stan, Kyle, Cartman and Kenny"
              title="Stan, Kyle, Cartman and Kenny"
              height="300px"
              style={{ position: "absolute", right: "0", top: "20%" }}
            ></img>
          </AspectRatio.Root>
        </section>
      </main>
    </>
  );
}
